apiVersion: v1
kind: Service
metadata:
  name: gitops-flask-service
  namespace: default
spec:
  type: LoadBalancer # Triggers AWS to give your Flask app its own public URL
  ports:
    - port: 80 # Public web port
      targetPort: 5000 # Directs traffic to Flask's internal port
  selector:
    app: gitops-flask

    